### ISSUE TITLE
Unable to modify first controller appliance

### ISSUE THREAD

**Issue by ppira** [appgate/terraform-provider-appgate-sdp#92]
Hi

I'm not able to modify the first controller with terraform. As it is created outside terraform (vmware clone with seed-file on iso) I need to find its ID and define it in the "appgate_appliance" resource.

```
data "appgate_site" "default_site" {
  site_name = "Default site"
}

data "appgate_appliance" "default_appliance" {
  appliance_name = "appgate1_example_com"
}

resource "appgate_appliance" "appgate1" {
  name     = data.appgate_appliance.default_appliance.appliance_name
  id     = data.appgate_appliance.default_appliance.appliance_id
  hostname = "appgate1.example.com"
  site  = data.appgate_site.default_site.id
<snip>
```
This will just fail with:
```
Error: Invalid or unknown key

  on appliance.tf line 11, in resource "appgate_appliance" "appgate1_example_com":
  11:   id     = data.appgate_appliance.default_appliance.appliance_id
```

If I remove the "id =" line it just wants to create a new appliance. I know I can import the appliance to my tfstate but that is not very automation-friendly.

**Comment by danijeel** [comment]
ah, yes this is a chicken-and-egg problem.
since the controller came first, we can never create the first controller from terraform, but we can import it.

https://www.terraform.io/docs/cli/import/index.html#currently-state-only

first create a stub of the resource in your tf file


```tf
# main.tf
resource "appgate_appliance" "first_controller" {}
```

then import the remote state
```sh
$ terraform import 'appgate_appliance.first_controller' 01ad97f1-efe8-4a81-9e5f-93ab0ac9846d
```

`01ad97f1-efe8-4a81-9e5f-93ab0ac9846d` is the UUID for appliance, you can for example see it in the dashboard URI
https://your.controller.appgate.com:8443/ui/appliances/edit/01ad97f1-efe8-4a81-9e5f-93ab0ac9846d

then run 
```sh
$ terraform state show appgate_appliance.first_controller
```

from your CLI 
https://www.terraform.io/docs/cli/commands/state/show.html

this should generate a stub of your resource to stdout, which you can replace from the one with step 1,
resolve any conflicts it may have generated (for example I needed to remove appliance_id, id and connector attributes)

then you should have the first controller in a terraform resource format.

I just tried this with `terraform v0.14.5` on appliance 5.2 and 5.3.
It might be diffrent in earlier versions of terraform.

**Comment by ppira** [comment]
Well, my use case is automating a lot of single appliance deployments. I would really like to have a solution that is not dependent on "terraform import".

**Comment by danijeel** [comment]
I believe this is a limitation of terraform itself, as they state in the documentation, they might solve it in future releases, until then import is the only option I am aware of. If you come up with another solution, let me know. Though you shouldn't need to import anything else expect the first controller, since the rest of the resources can be created from this provider.

**Comment by ppira** [comment]
Ok, that is an unfortunate limitation. Any plans on implementing an Ansible module?

**Comment by danijeel** [comment]
> Ok, that is an unfortunate limitation. Any plans on implementing an Ansible module?

No, no plans for ansible.


We have 2 tools for infrastructure as code for Appgate, this terraform provider, and https://github.com/appgate/sdp-operator. The SDP operator is built for Kubernetes in mind, but could be used as a stand alone tool too to configure appgate resources, similar to how we do it in terraform.

This might be suitable for your use case.

**Comment by danijeel** [comment]
I will close this issue since I deem this issue is a generic terraform issue, and not for this provider.
